### PR TITLE
fixed drawing context’s frame

### PR DESCRIPTION
**Pull request by bielikb**
This fixes problem, when drawing appeared not follow the cursor/user's finger.

Also image context was not relased in case the current context couldn't be obtained

### CODE REVIEW

**Comment by bielikb** [comment]
@rimh pls check this PR and let me know what you think ;)

**Comment by rimh** [comment]
@bielikb 
Apologies for very late reply, I'm quite busy.
Actually, I had refactored the same part as your PR in my next commit. 
However, I will accept your PR 😄 

Please fix your PR. 
Do not change about tab or indent,  just change on context part. 🙇 
Thank you for comment and PR.

**Comment by bielikb** [comment]
@rimh haha. ok no worries. if it's fixed in your next commit, we can close this one ;)

**Comment by rimh** [comment]
Thank you.

**Pull request closed without merging**
